version: '3.8'

services:
  papyrus-apiv2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION:-18-alpine}
    container_name: papyrus-apiv2
    restart: unless-stopped

    environment:
      # 🌐 Servidor
      PORT: ${PORT:-4001}
      HOST: ${HOST:-0.0.0.0}
      NODE_ENV: ${NODE_ENV:-production}

      # 💾 Banco de dados PostgreSQL
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}

      # 🔑 API Keys Administrativas
      ADMIN_API_KEYS: ${ADMIN_API_KEYS}

      # ⚙️ Rate Limiting
      RATE_LIMIT_DEFAULT: ${RATE_LIMIT_DEFAULT}
      RATE_LIMIT_WINDOW: ${RATE_LIMIT_WINDOW}

      # 🎨 PDF Generation
      PDF_ENGINE: ${PDF_ENGINE}
      PDF_TIMEOUT: ${PDF_TIMEOUT}
      PDF_QUALITY: ${PDF_QUALITY}

      # 🔒 Security
      CORS_ORIGIN: ${CORS_ORIGIN}
      HELMET_ENABLED: ${HELMET_ENABLED}
      JWT_SECRET: ${JWT_SECRET}

      # 📈 Performance
      ENABLE_COMPRESSION: ${ENABLE_COMPRESSION}
      CACHE_TEMPLATES: ${CACHE_TEMPLATES}
      CACHE_DURATION: ${CACHE_DURATION}

      # 🗄️ MinIO
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_PUBLIC_URL: ${S3_PUBLIC_URL}      

    volumes:
      - papyrus_pdf_cache:/app/cache
      - papyrus_logs:/app/logs
      - papyrus_uploads:/app/uploads
      - papyrus_templates:/app/custom-templates

    ports:
      - "${PORT:-4000}:4000"

    networks:
      - papyrus-network

    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "portainer.webhook=true"
      - "papyrus.version=${PAPYRUS_VERSION:-latest}"

volumes:
  papyrus_pdf_cache:
    driver: local
  papyrus_logs:
    driver: local
  papyrus_uploads:
    driver: local
  papyrus_templates:
    driver: local

networks:
  papyrus-network:
    driver: bridge
