version: '3.8'

services:
  # ========== API PAPYRUS ==========
  papyrus-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION:-18-alpine}
    container_name: papyrus-api
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-4000}
      HOST: ${HOST:-0.0.0.0}
      
      DB_CLIENT: ${DB_CLIENT:-pg}
      DB_HOST: ${DB_HOST:-postgres-shared}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-papyrus_user}
      DB_PASSWORD: ${DB_PASSWORD:-papyrus_secure_2024}
      DB_DATABASE: ${DB_DATABASE:-papyrus_db}

      ADMIN_API_KEYS: ${ADMIN_API_KEYS:-demo-key:10,premium-key:100,unlimited-key:0}

      RATE_LIMIT_DEFAULT: ${RATE_LIMIT_DEFAULT:-10}
      RATE_LIMIT_WINDOW: ${RATE_LIMIT_WINDOW:-60000}

      PDF_ENGINE: ${PDF_ENGINE:-puppeteer}
      PDF_TIMEOUT: ${PDF_TIMEOUT:-30000}
      PDF_QUALITY: ${PDF_QUALITY:-high}

      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      HELMET_ENABLED: ${HELMET_ENABLED:-true}
      JWT_SECRET: ${JWT_SECRET:-your_super_secret_jwt_key_here_change_in_production}

      ENABLE_COMPRESSION: ${ENABLE_COMPRESSION:-true}
      CACHE_TEMPLATES: ${CACHE_TEMPLATES:-true}
      CACHE_DURATION: ${CACHE_DURATION:-30000}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_TO_FILE: ${LOG_TO_FILE:-false}
      
    volumes:
      - papyrus_pdf_cache:/app/cache
      - papyrus_logs:/app/logs
      - papyrus_uploads:/app/uploads

    ports:
      - "${PAPYRUS_API_PORT:-4000}:4000"

    networks:
      - papyrus-internal
      - shared-database-network
      
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
      
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # ========== REDIS PARA CACHE ==========
  papyrus-redis:
    image: redis:7-alpine
    container_name: papyrus-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${PAPYRUS_REDIS_PASSWORD:-papyrus_redis_2024}
    volumes:
      - papyrus_redis_data:/data
    ports:
      - "${PAPYRUS_REDIS_PORT:-6379}:6379"
    networks:
      - papyrus-internal
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - redis